version: "3.7"
services:
  api:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: ruhanoliveira/node-10-alpine
    container_name: aws-lambda-express-test
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports:
      - "3000:3000"
    networks:
      - aws-lambda-express-test

networks:
  aws-lambda-express-test:
    name: aws-lambda-express-test
    driver: bridge